var itemList=document.querySelector('#items');
itemList.parentElement.style.color='green';
itemList.firstElementChild.style.backgroundColor='yellow';
itemList.firstElementChild.textContent='banana';
itemList.lastElementChild.style.backgroundColor='red';
itemList.lastElementChild.textContent='apples';
itemList.previousElementSibling.textContent='select fruites';
var items = document.querySelector('.list-group-item:nth-child(2)');
items.textContent='orange';
items.style.backgroundColor='orange';
var items3 = document.querySelector('.list-group-item:nth-child(3)');
items3.style.backgroundColor='purple';
items3.textContent='blackberry';
var newDiv=document.createElement('div');
newDiv.className='newTitle';
newDiv.id='title1';
var newDivText=document.createTextNode('Fruit Selections');
newDiv.appendChild(newDivText);
var container = document.querySelector('header .container');
var h1=document.querySelector('header h1');
console.log(newDiv);
container.insertBefore(newDiv,h1);
newDiv.style.color='black';
